version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:  
          requires:
            - build
          filters:
            branches:
              only: main
jobs:
  build:
    docker:
      - image: cimg/node:14.17.6
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install the dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - "./node_modules"
      - run: mkdir ~/junit
      - run:
          name: check code style
          command: npx eslint 'src/**'
      - run:
          name: tests and generates coverage report
          command: |
            npm run test:coveralls -v $(circleci tests glob "**/*.spec.ts" "**/*.test.ts", "**/test/**" | circleci tests split --split-by=timings)
      - run: 
          command: cp junit.xml ~/junit/
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
        
